/*
 * generated by Xtext 2.9.1
 */
package no.javatime.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ModelStandaloneSetup extends ModelStandaloneSetupGenerated {

	def static void doSetup() {
		new ModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
