/**
 * generated by Xtext 2.9.1
 */
package no.javatime.lang.model.provider;


import java.util.Collection;
import java.util.List;

import no.javatime.lang.model.ModelElementType;
import no.javatime.lang.model.ModelFactory;
import no.javatime.lang.model.ModelPackage;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.eclipse.xtext.common.types.TypesFactory;

import org.eclipse.xtext.xbase.annotations.xAnnotations.XAnnotationsFactory;

import org.eclipse.xtext.xtype.XtypeFactory;

/**
 * This is the item provider adapter for a {@link no.javatime.lang.model.ModelElementType} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ModelElementTypeItemProvider extends ElementItemProvider {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ModelElementTypeItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addTypeNamePropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Type Name feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void addTypeNamePropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_ModelElementType_typeName_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_ModelElementType_typeName_feature", "_UI_ModelElementType_type"),
				 ModelPackage.Literals.MODEL_ELEMENT_TYPE__TYPE_NAME,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.GENERIC_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MODEL_ELEMENT_ANNOTATIONS);
			childrenFeatures.add(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE);
			childrenFeatures.add(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS);
			childrenFeatures.add(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MEMBERS);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns ModelElementType.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/ModelElementType"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((ModelElementType)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_ModelElementType_type") :
			getString("_UI_ModelElementType_type") + " " + label;
	}
	

	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(ModelElementType.class)) {
			case ModelPackage.MODEL_ELEMENT_TYPE__TYPE_NAME:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case ModelPackage.MODEL_ELEMENT_TYPE__MODEL_ELEMENT_ANNOTATIONS:
			case ModelPackage.MODEL_ELEMENT_TYPE__SUPER_TYPE:
			case ModelPackage.MODEL_ELEMENT_TYPE__IMPLEMENTS:
			case ModelPackage.MODEL_ELEMENT_TYPE__MEMBERS:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MODEL_ELEMENT_ANNOTATIONS,
				 XAnnotationsFactory.eINSTANCE.createXAnnotation()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmParameterizedTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmGenericArrayTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmWildcardTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmAnyTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmMultiTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmDelegateTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmSynonymTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmUnknownTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 TypesFactory.eINSTANCE.createJvmInnerTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 XtypeFactory.eINSTANCE.createXFunctionTypeRef()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE,
				 XtypeFactory.eINSTANCE.createXComputedTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmParameterizedTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmGenericArrayTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmWildcardTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmAnyTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmMultiTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmDelegateTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmSynonymTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmUnknownTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 TypesFactory.eINSTANCE.createJvmInnerTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 XtypeFactory.eINSTANCE.createXFunctionTypeRef()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS,
				 XtypeFactory.eINSTANCE.createXComputedTypeReference()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MEMBERS,
				 ModelFactory.eINSTANCE.createMember()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MEMBERS,
				 ModelFactory.eINSTANCE.createField()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.MODEL_ELEMENT_TYPE__MEMBERS,
				 ModelFactory.eINSTANCE.createOperation()));
	}

	/**
	 * This returns the label text for {@link org.eclipse.emf.edit.command.CreateChildCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
		Object childFeature = feature;
		Object childObject = child;

		boolean qualify =
			childFeature == ModelPackage.Literals.MODEL_ELEMENT_TYPE__SUPER_TYPE ||
			childFeature == ModelPackage.Literals.MODEL_ELEMENT_TYPE__IMPLEMENTS;

		if (qualify) {
			return getString
				("_UI_CreateChild_text2",
				 new Object[] { getTypeText(childObject), getFeatureText(childFeature), getTypeText(owner) });
		}
		return super.getCreateChildText(owner, feature, child, selection);
	}

}
