/**
 * generated by Xtext 2.9.1
 */
package no.javatime.lang.model.provider;


import java.util.Collection;
import java.util.List;

import no.javatime.lang.model.ModelFactory;
import no.javatime.lang.model.ModelPackage;
import no.javatime.lang.model.PackageDeclaration;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ViewerNotification;
import org.eclipse.xtext.xtype.XtypeFactory;

/**
 * This is the item provider adapter for a {@link no.javatime.lang.model.PackageDeclaration} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PackageDeclarationItemProvider extends ElementItemProvider {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PackageDeclarationItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

		}
		return itemPropertyDescriptors;
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(ModelPackage.Literals.PACKAGE_DECLARATION__IMPORT_SECTION);
			childrenFeatures.add(ModelPackage.Literals.PACKAGE_DECLARATION__PACKAGE_ELEMENTS);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns PackageDeclaration.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/PackageDeclaration"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		String label = ((PackageDeclaration)object).getName();
		return label == null || label.length() == 0 ?
			getString("_UI_PackageDeclaration_type") :
			getString("_UI_PackageDeclaration_type") + " " + label;
	}
	

	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(PackageDeclaration.class)) {
			case ModelPackage.PACKAGE_DECLARATION__IMPORT_SECTION:
			case ModelPackage.PACKAGE_DECLARATION__PACKAGE_ELEMENTS:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.PACKAGE_DECLARATION__IMPORT_SECTION,
				 XtypeFactory.eINSTANCE.createXImportSection()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.PACKAGE_DECLARATION__PACKAGE_ELEMENTS,
				 ModelFactory.eINSTANCE.createElement()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.PACKAGE_DECLARATION__PACKAGE_ELEMENTS,
				 ModelFactory.eINSTANCE.createPackageDeclaration()));

		newChildDescriptors.add
			(createChildParameter
				(ModelPackage.Literals.PACKAGE_DECLARATION__PACKAGE_ELEMENTS,
				 ModelFactory.eINSTANCE.createModelElementType()));
	}

}
