/*
 * generated by Xtext 2.9.1
 */
package no.javatime.lang.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ModelUiModule extends AbstractModelUiModule {
}
